#!/bin/bash
cd "$(dirname "$0")"

qemu-system-m68k \
 -M q800 \
 -m 128 \
 -bios "Quadra800.rom" \
 -display gtk \
 -g 1152x870x8 \
 -drive file=pram-macos.img,format=raw,if=mtd \
 -device scsi-hd,scsi-id=0,drive=hd0 \
 -drive file=MacOS7.5.3.img,format=raw,media=disk,if=none,id=hd0 \
 -device scsi-cd,scsi-id=3,drive=cd0 \
 -drive file=MacOS7.5.3.iso,format=raw,media=disk,if=none,id=cd0 \
 -monitor stdio
