#!/bin/bash

RETRO68_SHA=`cat /build/buildinfo/retro68.sha`
MLTON_SHA=`cat /build/buildinfo/mlton.sha`
TWELF_SHA=`cat /build/buildinfo/twelf.sha`
TWELF_MAC_SHA=`cat /root/app/twelf-mac.sha`

cat <<EOF
/*
 * This file is automatically generated by docker/scripts/buildinfo.sh.
 * Edits may be lost.
 */
char *build_info =
  "github:agoode/Retro68 at:      $RETRO68_SHA\r"
  "github:agoode/mlton at:        $MLTON_SHA\r"
  "github:agoode/twelf at:        $TWELF_SHA\r"
  "github:jcreedcmu/twelf-mac at: $TWELF_MAC_SHA\r";
EOF
