#!/bin/bash

RETRO68_SHA=`cat /build/buildinfo/retro68.sha`
MLTON_SHA=`cat /build/buildinfo/mlton.sha`
TWELF_SHA=`cat /build/buildinfo/twelf.sha`

cat <<EOF
/*
 * This file is automatically generated by docker/scripts/buildinfo.sh.
 * Edits may be lost.
 */
char *build_info =
  "Retro68 at commit: $RETRO68_SHA\r"
  "MLTon at commit: $MLTON_SHA\r"
  "Twelf at commit: $TWELF_SHA\r";
EOF
